# Generated by Django 4.2.13 on 2024-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('unemployment_duration', models.CharField(max_length=100)),
                ('current_status1', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status2', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status3', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status4', models.CharField(blank=True, max_length=100, null=True)),
                ('identity1', models.CharField(blank=True, max_length=100, null=True)),
                ('identity2', models.CharField(blank=True, max_length=100, null=True)),
                ('identity3', models.CharField(blank=True, max_length=100, null=True)),
                ('identity4', models.CharField(blank=True, max_length=100, null=True)),
                ('identity5', models.CharField(blank=True, max_length=100, null=True)),
                ('identity6', models.CharField(blank=True, max_length=100, null=True)),
                ('identity7', models.CharField(blank=True, max_length=100, null=True)),
                ('identity8', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('name', 'gender', 'age', 'education', 'unemployment_duration')},
            },
        ),
    ]
