# Generated by Django 4.2.13 on 2024-05-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_status1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_status2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_status3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_status4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='identity1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='identity2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='identity3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='identity4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='identity5',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='identity6',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='identity7',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='identity8',
        ),
        migrations.CreateModel(
            name='employee_identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='employee_current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
