# Generated by Django 4.2.13 on 2024-05-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_identity',
            options={'verbose_name_plural': 'employee_identities'},
        ),
        migrations.AlterUniqueTogether(
            name='employee_current',
            unique_together={('employee_name', 'current_status')},
        ),
        migrations.AlterUniqueTogether(
            name='employee_identity',
            unique_together={('employee_name', 'identity')},
        ),
    ]
