# Generated by Django 4.2.13 on 2024-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='計畫名稱', max_length=100)),
                ('division', models.CharField(db_column='所屬科室', max_length=100)),
                ('type', models.CharField(db_column='計畫別', max_length=100)),
                ('purpose', models.TextField(db_column='目的')),
                ('age', models.CharField(db_column='適用年齡', max_length=100)),
                ('available', models.TextField(db_column='適用對象')),
                ('conditions', models.TextField(db_column='對象條件')),
                ('requirements', models.TextField(db_column='申請資格及條件')),
                ('salary', models.TextField(db_column='核薪方式')),
                ('benefits', models.TextField(db_column='給付標準')),
                ('benefit_interval', models.TextField(db_column='給付期限')),
                ('documents', models.TextField(db_column='應備文件')),
                ('keywords', models.TextField(db_column='關鍵字')),
                ('apply_method', models.TextField(db_column='申請方式')),
            ],
        ),
    ]
