# Generated by Django 4.2.13 on 2024-06-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_rename_plan_employer_plan_employer_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(db_column='單位類型', max_length=100)),
                ('employment_insurance', models.CharField(db_column='是否為就保單位', max_length=100)),
                ('subsidy_requirement', models.CharField(blank=True, db_column='補助需求項目', max_length=100, null=True)),
            ],
        ),
    ]
