# Generated by Django 4.2.13 on 2024-05-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan_employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(db_column='計畫名稱', max_length=100, unique=True)),
                ('plan_type', models.CharField(blank=True, db_column='計畫別', max_length=100, null=True)),
                ('required_employee_current', models.CharField(db_column='就業狀態', default='unemployed', max_length=100)),
                ('required_employee_gender', models.CharField(db_column='性別限定', default='None', max_length=100)),
                ('employee_age_lower_bound', models.IntegerField(db_column='年齡下限', default=0)),
                ('employee_age_upper_bound', models.IntegerField(db_column='年齡上限', default=0)),
                ('employee_unemployment_duration_without_identity', models.IntegerField(db_column='失業週期(無特殊身份別)', default=0)),
                ('employee_unemployment_duration_with_identity', models.IntegerField(db_column='失業週期(有特殊身份別)', default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
