# Generated by Django 4.2.13 on 2024-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(db_column='計畫名稱', max_length=100)),
                ('division', models.CharField(db_column='所屬科室', max_length=100)),
                ('plan_type', models.CharField(blank=True, db_column='計畫別', max_length=100, null=True)),
                ('purpose', models.TextField(blank=True, db_column='目的', null=True)),
                ('apply', models.TextField(blank=True, db_column='申請資格及條件', null=True)),
                ('benefit', models.TextField(blank=True, db_column='給付標準', null=True)),
                ('benefit_interval', models.TextField(blank=True, db_column='給付期限', null=True)),
                ('document_required', models.TextField(blank=True, db_column='應備文件', null=True)),
                ('apply_method', models.TextField(blank=True, db_column='申請方式', null=True)),
                ('contact', models.TextField(blank=True, db_column='計畫窗口', null=True)),
                ('phone', models.CharField(blank=True, db_column='電話', max_length=100, null=True)),
            ],
        ),
    ]
