# Generated by Django 4.2.13 on 2024-05-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_employee_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan_employee',
            options={'ordering': ['id'], 'verbose_name_plural': 'plan_employee'},
        ),
        migrations.AlterModelOptions(
            name='plan_employee_details',
            options={'verbose_name_plural': 'plan_employee_details'},
        ),
    ]
