# Generated by Django 4.2.13 on 2024-05-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_plan_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan_employee_details',
            options={'ordering': ['id'], 'verbose_name_plural': 'plan_employee_details'},
        ),
    ]
